export const solar = "/solar pannel desert.jpg"
export const sunburnspanel = "/solar-panels.jpg"
export const panelicon = "/panelicon.png"
export const earthInCar = "/earth-in-trunk.jpg"
export const KhalidAlFalih = "/Khalid al-Falih.jpg"
export const litreDisel = "/120 litre.jpg"